import type { Challenge } from "@/types/app";

export const CHALLENGES: Challenge[] = [
  {
    id: 1,
    title: "Common Ground Connect",
    description: "Find 1 teammate. 5 minutes. 3 real things in common. Not the obvious ones.",
    day: "Day 1",
    points: 1,
    requiresUpload: false,
    requiresText: true,
    placeholder: "What were the 3 things you found in common? Describe the moment.",
  },
  {
    id: 2,
    title: "Creative Tribe Snap",
    description: "One creative tribe photo. No boring selfies. Post it and tag everyone.",
    day: "Day 1",
    points: 1,
    requiresUpload: true,
    requiresText: false,
  },
  {
    id: 3,
    title: "You Crossed My Mind",
    description: "Someone will cross your mind today. After the session, open their chat. Write your real words. Not a forward. Just you.",
    day: "Day 1",
    points: 5,
    requiresUpload: true,
    requiresText: false,
  },
  {
    id: 4,
    title: "Real Voice Note",
    description: "90 seconds. One person. No script. No re-record. Hit send on the first one.",
    day: "Day 1",
    points: 5,
    requiresUpload: false,
    requiresText: true,
    placeholder: "Who did you send it to and what did you say? Be honest.",
  },
  {
    id: 5,
    title: "Connect Their Dots",
    description: "When the conversation is already real, share your link. Points only when your friend applies.",
    day: "Days 1-3",
    points: 10,
    requiresUpload: false,
    requiresText: false,
    isReferral: true,
  },
  {
    id: 6,
    title: "Caught You Being Great",
    description: "Find someone with a quality you admire. Walk up. Tell them exactly what you saw. Be specific.",
    day: "Day 2",
    points: 3,
    requiresUpload: false,
    requiresText: true,
    placeholder: "Who did you catch being great? What exactly did you see? What did you tell them?",
  },
  {
    id: 7,
    title: "Tribe Time Capsule",
    description: "One sentence to your future self. Sealed. Collected by your tribe leader. Opened one year from today.",
    day: "Day 2",
    points: 2,
    requiresUpload: false,
    requiresText: true,
    placeholder: "Write your one sentence to your future self. Make it true.",
  },
  {
    id: 8,
    title: "The Story I Almost Didn't Tell",
    description: "Post the moment you nearly didn't come here. The doubt. The decision. Under 200 words. Make it true.",
    day: "Day 2",
    points: 3,
    requiresUpload: false,
    requiresText: true,
    placeholder: "Tell the story. Under 200 words. The doubt, the decision, the moment.",
    maxWords: 200,
  },
  {
    id: 9,
    title: "3-Day Real Streak",
    description: "One real post. Every day. All 3 days. No templates. Just one honest moment each day.",
    day: "Days 1-3",
    points: 3,
    requiresUpload: true,
    requiresText: false,
    streakDays: 3,
  },
];

export function isStreakChallenge(challengeId: number): boolean {
  const challenge = CHALLENGES.find((c) => c.id === challengeId);
  return challenge?.streakDays !== undefined && challenge.streakDays > 0;
}
